parameters:
  Docker.Registry: ""

jobs:
  - job: docker_build
    dependsOn:
    - app_build
    displayName: "docker build & push"
    pool:
      vmImage: 'ubuntu-16.04'
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        submodules: recursive
        persistCredentials: true   
      - task: Npm@1
        displayName: "npm install"
        inputs:
          command: install
          workingDir: "$(System.DefaultWorkingDirectory)/ng-git-meetup"      
      - task: Npm@1
        displayName: "npm run build"
        inputs:
          command: custom
          customCommand: "run build"
          workingDir: "$(System.DefaultWorkingDirectory)/ng-git-meetup"              
      - task: Docker@2
        displayName: "[docker] login"
        inputs:
          command: login
          containerRegistry: ${{ parameters['Docker.Registry'] }}
      - task: Docker@2
        displayName: "[docker] build & push"
        inputs:
          command: buildAndPush
          containerRegistry: ${{ parameters['Docker.Registry'] }}
          repository: girlsintechpl/ng-git-meetup
          Dockerfile: $(System.DefaultWorkingDirectory)/ng-git-meetup/Dockerfile
          buildContext: $(System.DefaultWorkingDirectory)/ng-git-meetup
          tags: |
            latest
            $(Build.BuildNumber)
      - task: Docker@2
        displayName: "[docker] logout"
        inputs:
          command: logout
          containerRegistry: ${{ parameters['Docker.Registry'] }}